project:
  type: website
  output-dir: "docs"
  resources:
    - "files/"

website:
  title: "Emma Ebowe"
  favicon: "favicon-32x32.png"
  search: false
  navbar:
    title: false
    background: "#c4d2df"
    pinned: true
    left:
    - text: "Welcome"
      href: index.qmd

    right:
    - text: "Research"
      href: research.qmd
    - text: "Teaching"
      href: teaching.qmd
    - text: "CV"
      href: cv/cv_aug2025.pdf
    - text: "Service"
      href: service.qmd
    - text: "{{< bi envelope >}}"
      href: mailto:evebowe@wm.edu
  page-footer:
    right: "Â© 2024 Emma Ebowe. All rights reserved."
  google-analytics:
    tracking-id: "G-WC1DHY5K8W"

format:
  html:
    theme:
    - lux
    - custom.scss
    css: styles.css
    toc: false
    linkcolor: darkblue
    fontsize: 12.5pt

editor: visual

